### ISSUE TITLE
Generate public folder for css

### ISSUE THREAD

**Issue by lukasbrodbeck** [Becklyn/kaba-shelf-less#1]
Instead of autogenerating the target folder when using less taks, the console is throwing an error saying that the folder doesn't exist.

![bildschirmfoto-2016-12-13-um-14 47 13](https://cloud.githubusercontent.com/assets/12810590/21142656/7ce9ed8c-c143-11e6-8b08-8b7fc015208a.png)

**Comment by apfelbox** [comment]
Fixed in 0.2.1
